### Example of 1-D Array

In [1]:
import numpy

In [2]:
numpy.array([1,2,3])

array([1, 2, 3])

### Example of 2-D Array

In [3]:
import numpy as np

In [4]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.array([1,2,3,4],ndmin=2)

array([[1, 2, 3, 4]])

### d-type Complex

In [6]:
a = np.array([1,2,3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


### Shape of an array

In [7]:
a = np.array([[1,2,3],[4,5,6]])

In [8]:
a.shape

(2, 3)

### Routine Creation

In [9]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [10]:
a = np.zeros((5,), dtype=np.int)
print(a)

[0 0 0 0 0]


In [11]:
a = np.zeros((2,2))

In [12]:
a

array([[0., 0.],
       [0., 0.]])

### Convert list or tuple to ndarray

In [13]:
x = [1,2,3]
y = (1,2,3)

In [14]:
a = np.asarray(x)
b = np.asarray(y)
print(a)
print(b)

[1 2 3]
[1 2 3]


### Slicing

In [27]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
s = a[2:7:2]
print(s)

[2 4 6]


### Example

In [29]:
a = np.array([0,30,45,60,90])
print(np.sin(a*np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]


### Example of Statistical Function 

In [36]:
a = np.array([[3, 7, 5], [8, 4, 3], [2, 4, 9]])
print(a)

[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [37]:
np.amin(a,1)    ### Row-wise 

array([3, 3, 2])

In [38]:
np.amin(a,0)    ### Column-wise 

array([2, 4, 3])